export const FETCH_USER_LOGIN = 'FETCH_USER_LOGIN';
export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING';
export const USER_LOGIN_REJECT = 'USER_LOGIN_REJECT';

export const FETCH_USER_REGISTER = 'FETCH_USER_REGISTER';
export const USER_REGISTER_PENDING = 'USER_REGISTER_PENDING';
export const USER_REGISTER_REJECT = 'USER_REGISTER_REJECT';

export const FETCH_USER_LOGOUT = 'FETCH_USER_LOGOUT';
export const USER_LOGOUT_PENDING = 'USER_LOGOUT_PENDING';
export const USER_LOGOUT_REJECT = 'USER_LOGOUT_REJECT';