export const FETCH_ADD_BASKET= 'FETCH_ADD_BASKET';
export const ADD_BASKET_PENDING = 'ADD_BASKET_PENDING';
export const ADD_BASKET_REJECT = 'ADD_BASKET_REJECT';
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET"
export const PLUS_AMOUNT ="PLUS_AMOUNT"
export const MINUS_AMOUNT ="MINUS_AMOUNT"