export const FETCH_ADD_FAVORITE= 'FETCH_ADD_FAVORITE';
export const ADD_FAVORITE_PENDING = 'ADD_FAVORITE_PENDING';
export const ADD_FAVORITE_REJECT = 'ADD_FAVORITE_REJECT';
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE"
