export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST';
export const PRODUCT_PENDING = 'PRODUCT_PENDING';
export const PRODUCT_REJECT = 'PRODUCT_REJECT';

export const FETCH_PRODUCT_CATEGORY = 'FETCH_PRODUCT_CATEGORY';
export const PRODUCT_CATEGORY_PENDING = 'PRODUCT_CATEGORY_PENDING';
export const PRODUCT_CATEGORY_REJECT = 'PRODUCT_CATEGORY_REJECT';
